apiVersion: run.tanzu.vmware.com/v1alpha1  #TKGS API endpoint
kind: TanzuKubernetesCluster               #required parameter
metadata:
  name: tkgs-test01                   #cluster name, user defined
  namespace: test01             #vsphere namespace
spec:
  distribution:
    version: v1.20.9                        #Resolves to latest TKR 1.19 version
  topology:
    controlPlane:
      count: 1                             #number of control plane nodes
      class: best-effort-small           #vmclass for control plane nodes
      storageClass: workload-management-storage-policy #storageclass for control plane
    workers:
      count: 1                             #number of worker nodes
      class: best-effort-small            #vmclass for worker nodes
      storageClass: workload-management-storage-policy   #storageclass for worker nodes

