apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    configured-by: vmware-tsm
    owner: operator-deployer
  name: tsmclusters.tsm.vmware.com
spec:
  conversion:
    strategy: None
  group: tsm.vmware.com
  names:
    kind: TsmCluster
    listKind: TsmClusterList
    plural: tsmclusters
    singular: tsmcluster
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uuid:
                  type: string
                version:
                  type: string
